# Use official Python base image
FROM python:3.10-slim

# Set working directory inside container
WORKDIR /app

# Install dependencies (system packages if needed)
RUN apt-get update && apt-get install -y \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# Install Python dependencies
RUN pip install --upgrade pip
RUN pip install numpy==1.26.3
RUN pip install streamlit==1.30.0
RUN pip install tensorflow==2.15.0.post1

# Copy your project files into the container
COPY . .

# Expose Streamlit port
EXPOSE 8080

# Run your Streamlit app
CMD ["streamlit", "run", "app.py"]
